on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      TIDY_FIA_PASSWORD: ${{ secrets.TIDY_FIA_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install macOS system dependencies
        if: runner.os == 'macos'
        run: brew install gdal proj

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Setup .Renviron
        run: |
          echo "TIDY_FIA_PASSWORD=${{ secrets.TIDY_FIA_PASSWORD }}" >> $HOME/.Renviron

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

      - name: Setup tmate session
        env:
          DEBUG_MODE: ${{ secrets.ACTIONS_RUNNER_DEBUG && secrets.ACTIONS_STEP_DEBUG }}
        uses: mxschmitt/action-tmate@v3
        if: failure() && env.DEBUG_MODE
        timeout-minutes: 60